# vim: set tabstop=2 shiftwidth=2 ft=yaml expandtab:
---
- shell: |
    set -o pipefail
    cd /home/cloud-user
    bash quickstart.sh --release pike --requirements /home/cloud-user/internal-requirements.txt --bootstrap --tags all --nodes /home/cloud-user/.quickstart/config/nodes/1ctlr_1comp.yml --working-dir /home/cloud-user/.quickstart --playbook dci-trigger.yml 127.0.0.2
  become: true
  become_user: root

- import_playbook: /home/cloud-user/.quickstart/add_host.yml
